# Build the container image
# docker build -t gcr.io/wordless-412000/github.com/rwbutts/wordless_api_go:$COMMIT_SHA -f Dockerfile 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_api_go:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_api_go:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'wordless-go', '--image', 'gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_api_go:$COMMIT_SHA', '--region', 'us-east4']
images:
- gcr.io/$PROJECT_ID/github.com/rwbutts/wordless_api_go:$COMMIT_SHA
